import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Box, Flex } from '@chakra-ui/react';
import Image, { ImageLoaderProps } from 'next/image';
import adaAndFado from 'images/adaAndFado.jpeg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Horses Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box display={{ base: 'none', md: 'flex' }}>
        <Image sizes="100vh" src={adaAndFado} alt="Ada" />
      </Box>
    </>
  );
}
